In [48]:
import numpy as np
import pandas as pd

In [49]:
headers_data = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

df = pd.read_csv(r'C:\Users\lenovo\Desktop\Machine Learning\Data Preprocessing\dataset_1.data', names = headers_data)
df.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [51]:
df.replace("?", np.nan, inplace = True)
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN

In [52]:
missing_value = df.isnull()
missing_value

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [53]:
for column in headers_data:
    print(column)
    print(missing_value[column].value_counts())

symboling
symboling
False    205
Name: count, dtype: int64
normalized-losses
normalized-losses
False    164
True      41
Name: count, dtype: int64
make
make
False    205
Name: count, dtype: int64
fuel-type
fuel-type
False    205
Name: count, dtype: int64
aspiration
aspiration
False    205
Name: count, dtype: int64
num-of-doors
num-of-doors
False    203
True       2
Name: count, dtype: int64
body-style
body-style
False    205
Name: count, dtype: int64
drive-wheels
drive-wheels
False    205
Name: count, dtype: int64
engine-location
engine-location
False    205
Name: count, dtype: int64
wheel-base
wheel-base
False    205
Name: count, dtype: int64
length
length
False    205
Name: count, dtype: int64
width
width
False    205
Name: count, dtype: int64
height
height
False    205
Name: count, dtype: int64
curb-weight
curb-weight
False    205
Name: count, dtype: int64
engine-type
engine-type
False    205
Name: count, dtype: int64
num-of-cylinders
num-of-cylinders
False    205
Name: count, dtype: int64
engine-size
engine-size
False    205
Name: count, dtype: int64
fuel-system
fuel-system
False    205
Name: count, dtype: int64
bore
bore
False    201
True       4
Name: count, dtype: int64
stroke
stroke
False    201
True       4
Name: count, dtype: int64
compression-ratio
compression-ratio
False    205
Name: count, dtype: int64
horsepower
horsepower
False    203
True       2
Name: count, dtype: int64
peak-rpm
peak-rpm
False    203
True       2
Name: count, dtype: int64
city-mpg
city-mpg
False    205
Name: count, dtype: int64
highway-mpg
highway-mpg
False    205
Name: count, dtype: int64
price
price
False    201
True       4
Name: count, dtype: int64

In [54]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [55]:
mean_nl = df['normalized-losses'].astype(float).mean()
mean_nl

122.0

In [56]:
df['normalized-losses'].replace(np.nan, mean_nl, inplace = True)
df.head()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_11448\3571620718.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['normalized-losses'].replace(np.nan, mean_nl, inplace = True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [61]:
mean_bore = df['bore'].astype(float).mean()

mean_stroke = df['stroke'].astype(float).mean()

mean_pr = df['peak-rpm'].astype(float).mean()

mean_hp = df['horsepower'].astype(float).mean()

print(mean_bore, mean_stroke, mean_pr, mean_hp)

3.3297512437810943 3.2554228855721394 5125.369458128079 104.25615763546797

In [63]:
df['bore'].replace(np.nan, mean_bore, inplace = True)
df['stroke'].replace(np.nan, mean_stroke, inplace = True)
df['peak-rpm'].replace(np.nan, mean_pr, inplace = True)
df['horsepower'].replace(np.nan, mean_hp, inplace = True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_11448\2771928128.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bore'].replace(np.nan, mean_bore, inplace = True)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_11448\2771928128.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['stroke'].replace(np.nan, mean_stroke, inplace = True)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_11448\2771928128.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['peak-rpm'].replace(np.nan, mean_pr, inplace = True)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_11448\2771928128.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].replace(np.nan, mean_hp, inplace = True)

In [67]:
df['num-of-doors'].value_counts().idxmax()

'four'

In [72]:
df['num-of-doors'].replace(np.nan, 'four', inplace = True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_11448\3692053418.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['num-of-doors'].replace(np.nan, 'four', inplace = True)

In [73]:
missing_value2 = df.isnull()
for column in headers_data:
    print(missing_value2[column].value_counts())

symboling
False    201
Name: count, dtype: int64
normalized-losses
False    201
Name: count, dtype: int64
make
False    201
Name: count, dtype: int64
fuel-type
False    201
Name: count, dtype: int64
aspiration
False    201
Name: count, dtype: int64
num-of-doors
False    201
Name: count, dtype: int64
body-style
False    201
Name: count, dtype: int64
drive-wheels
False    201
Name: count, dtype: int64
engine-location
False    201
Name: count, dtype: int64
wheel-base
False    201
Name: count, dtype: int64
length
False    201
Name: count, dtype: int64
width
False    201
Name: count, dtype: int64
height
False    201
Name: count, dtype: int64
curb-weight
False    201
Name: count, dtype: int64
engine-type
False    201
Name: count, dtype: int64
num-of-cylinders
False    201
Name: count, dtype: int64
engine-size
False    201
Name: count, dtype: int64
fuel-system
False    201
Name: count, dtype: int64
bore
False    201
Name: count, dtype: int64
stroke
False    201
Name: count, dtype: int64
compression-ratio
False    201
Name: count, dtype: int64
horsepower
False    201
Name: count, dtype: int64
peak-rpm
False    201
Name: count, dtype: int64
city-mpg
False    201
Name: count, dtype: int64
highway-mpg
False    201
Name: count, dtype: int64
price
False    201
Name: count, dtype: int64

In [69]:
df.dropna(subset = 'price', inplace = True)
df.reset_index(drop = True, inplace = True)

In [70]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [74]:
final_missing_values = df.isnull()
for column in headers_data:
    print(final_missing_values[column].value_counts())

symboling
False    201
Name: count, dtype: int64
normalized-losses
False    201
Name: count, dtype: int64
make
False    201
Name: count, dtype: int64
fuel-type
False    201
Name: count, dtype: int64
aspiration
False    201
Name: count, dtype: int64
num-of-doors
False    201
Name: count, dtype: int64
body-style
False    201
Name: count, dtype: int64
drive-wheels
False    201
Name: count, dtype: int64
engine-location
False    201
Name: count, dtype: int64
wheel-base
False    201
Name: count, dtype: int64
length
False    201
Name: count, dtype: int64
width
False    201
Name: count, dtype: int64
height
False    201
Name: count, dtype: int64
curb-weight
False    201
Name: count, dtype: int64
engine-type
False    201
Name: count, dtype: int64
num-of-cylinders
False    201
Name: count, dtype: int64
engine-size
False    201
Name: count, dtype: int64
fuel-system
False    201
Name: count, dtype: int64
bore
False    201
Name: count, dtype: int64
stroke
False    201
Name: count, dtype: int64
compression-ratio
False    201
Name: count, dtype: int64
horsepower
False    201
Name: count, dtype: int64
peak-rpm
False    201
Name: count, dtype: int64
city-mpg
False    201
Name: count, dtype: int64
highway-mpg
False    201
Name: count, dtype: int64
price
False    201
Name: count, dtype: int64

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    object
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  201 non-null    float64
 21  horsepower         201 non-null    object
 22  peak-rpm           201 non-null    object
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.0+ KB